package seventhSession;

public class ExceptionHandlingExmple {
	public static void main(String[] args) {
		int a = 23;
		int b = 0;
		int result =0;
		try {
			result= a / b;
			System.out.println("Completed division..");
			
		} catch (ArithmeticException exception) {
			b=1;
			result=a/b;
			System.out.println("Arithmetic Exception has occured");
		}
		System.out.println("The result is " + result);

		int []array={1,2};
		
		System.out.println(array[2]);
		
		
	}
}
